### ISSUE TITLE
Не отображает считыватель FLASH

### ISSUE THREAD

**Issue by ekorneechev** [bmakarenko/token-manager#12]
**$ cpconfig -hardware reader -view**
Nick name: FLASH
Connect name: 
Reader name: FLASH

Nick name: HDIMAGE
Connect name: 
Reader name: Структура дискеты на жестком диске

**$ csptest -keyset -enum_cont -fqcn -verifyc | iconv -f cp1251**
CSP (Type:80) v4.0.9019 KC1 Release Ver:4.0.9963 OS:Linux CPU:AMD64 FastCode:READY:DISABLED (EncryptECB; DecryptECB; DecryptCBC; GammaCNT; DecryptCFB; ).
AcquireContext: OK. HCRYPTPROV: 28892435
\\.\FLASH\ekorneechev_007724886690_06.05.19_11.59.02
\\.\HDIMAGE\Cert_Test_Crypto
OK.
Total: SYS: 0,020 sec USR: 0,100 sec UTC: 0,240 sec
[ErrorCode: 0x00000000]

А в token-maneger не отображается..

**Comment by bmakarenko** [comment]
Так и задумано

**Comment by ekorneechev** [comment]
А почему? Если из безопасности, то может какой-нибудь флажок/настройку приделать?
