### ISSUE TITLE
Нет параметра -verbose в КриптоПро 4.0.0-4

### ISSUE THREAD

**Issue by BcTpe4HbIu** [bmakarenko/token-manager#2]
В последних версиях КриптоПро нет параметра -verbose у certmgr. Из за его использования не отображаются сертификаты.
https://github.com/bmakarenko/token-manager/blob/master/token-manager.py#L257
https://github.com/bmakarenko/token-manager/blob/master/token-manager.py#L264

Так же нет в этой версии нет /usr/bin/cpconfig-amd64, есть только /usr/bin/cpconfig. https://github.com/bmakarenko/token-manager/blob/master/token-manager.py#L419

**Comment by bmakarenko** [comment]
/usr/bin/cpconfig-ia32 и /usr/bin/cpconfig-amd64 - это симлинк на /usr/bin/consolehelper, который позволяет запустить /usr/bin/cpconfig с правами рута(требуется для установки лицензии и установки токена в качестве считывателя) предложив пользователю ввести пароль. См. SPEC файл. 
По поводу КриптоПро 4.0 отпишусь позже, т.к. тесты с данной версией СКЗИ еще не проводились.

**Comment by bmakarenko** [comment]
Теперь ключ -verbose не используется для КриптоПро 4.0
