### ISSUE TITLE
Не виден сертификат в uMy

### ISSUE THREAD

**Issue by ddvlru** [bmakarenko/token-manager#3]
Сертификат увиделся на токене, по нажатии на кнопку «установить» установился в uMy, при переключении на uMy в консоль выводится сообщение:

Traceback (most recent call last):
  File "/usr/bin/token-manager.py", line 982, in select_token
    cert_issuer_cn = dict(re.findall(ur'([A-Z0-9\.]+?)=("?[\w \.\,0-9@\-\#\/\"]+"?)(?:, |$)', cert[1].decode('utf-8'), re.UNICODE))['CN']
KeyError: 'CN'

При этом в интерфейсе программы сертификат не отображается, а в консоли отображается с помощью certmgr -list -store uMy.

Рутокен ЭЦП, КриптоПро v4.0.9006 KC1 Release Ver:4.0.9708, квалифицированный сертификат.

Если что, dd@basealt.ru.

**Comment by bmakarenko** [comment]
Ошибка говорит о том, что у корневого сертификата УЦ, выдавшего этот сертификат, нет поля Common Name. Что очень странно. Прошу привести вывод certmgr -list -store uMy

**Comment by bmakarenko** [comment]
Проблема была, судя по всему, в поле O=ЗАО «ПФ «СКБ Контур»
Регэксп не понимал франзуцкие кавычки "ёлочки"

**Comment by sibskull** [comment]
Исправлено.
