### ISSUE TITLE
Неподдерживаемый токен

### ISSUE THREAD

**Issue by sibskull** [bmakarenko/token-manager#4]
1. Вставлена карта eSmart (без криптопрошного контейнера)
```
$ list_pcsc
ACS ACR38U-CCID 00 00
$ csptest -keyset -enum_cont -fqcn -verifyc -uniq
CSP (Type:80) v4.0.9006 KC1 Release Ver:4.0.9708 OS:Linux CPU:AMD64 FastCode:READY:AVX.
AcquireContext: OK. HCRYPTPROV: 6679571
\\.\HDIMAGE\test                                |\\.\HDIMAGE\HDIMAGE\\test.000\2EF8
OK.
Total: SYS: 0,010 sec USR: 0,200 sec UTC: 0,970 sec
[ErrorCode: 0x00000000]
HDIMAGE - локальный контейнер.
cas@cas ~ $ /usr/bin/opensc-tool --serial -r 0
sc_card_ctl(*, SC_CARDCTL_GET_SERIALNR, *) failed
cas@cas ~ $ echo $?
0
cas@cas ~ $ /usr/bin/opensc-tool -n -r 0
Unsupported card                                                                                                                        
cas@cas ~ $
```
То есть opensc-tool в случае ошибок работы с картой  возвращает 0. И нужно ориентироваться на выводимый текст в stdout и игнорировать stderr.

При запуске token-manager:
в консоли:
```
$ token-manager 
sc_card_ctl(*, SC_CARDCTL_GET_SERIALNR, *) failed
```
в диалоговом окне:
«Произошла ошибка:
invalid literal for int() with base 16: ''»

Ожидаемое поведение: ничего не делать.

**Comment by sibskull** [comment]
Теперь вставленный Рутокен:
```
$ list_pcsc                                                                                                                   
ACS ACR38U-CCID 00 00                                                                                                                   
Aktiv Rutoken lite 00 00               
$ /usr/bin/opensc-tool -l
# Detected readers (pcsc)
Nr.  Card  Features  Name
0    No              ACS ACR38U-CCID 00 00
1    Yes             Aktiv Rutoken lite 00 00
 cas@cas ~ $ /usr/bin/opensc-tool --serial -r 1
sc_card_ctl(*, SC_CARDCTL_GET_SERIALNR, *) failed
cas@cas ~ $ /usr/bin/opensc-tool --name -r 1
Unsupported card
$ csptest -keyset -enum_cont -fqcn -verifyc -uniq | iconv -f cp1251 | sed -n 's/^[^|]*|\(.*Aktiv Rutoken lite 00 00.*\)$/\1/p' 
\\.\Aktiv Rutoken lite 00 00\SCARD\rutoken_lt_319a5c53\0A00\93A9
\\.\Aktiv Rutoken lite 00 00\SCARD\rutoken_lt_319a5c53\0B00\7566
```

То есть на токене есть два контейнера. То есть использовать opensc-tool для анализа КриптоПрошных контейнеров - не очень хорошая идея.

**Comment by bmakarenko** [comment]
opensc-tool не используется для анализа криптопрошных контейнеров, а только для получения серийного номера токена. В вашем случае в кардридере не была вставлена смарт-карта, и поэтому opensc-tool не смог определить её серийный номер и выдал в stderr ошибку, а приложение, в свою очередь, получив из stdout(stderr при анализе вывода opensc-tool игнорируется) пустую строку не смогло преобразовать её из hex в dec, о чем и сообщило.
Во избежание подобного сделал try..except вокруг преобразования серийного номера в десятичное число. Если формат вывода не соответствует ожидаемому, в главном окне будет выводиться "<имя носителя> - сер. № б/н"
