### ISSUE TITLE
Ошибка декодирования

### ISSUE THREAD

**Issue by sibskull** [bmakarenko/token-manager#5]
При запуске token-manager при наличии сертификата в certmgr -list и отсутствии любых токенов пишет:
в консоли: "Card not present."
в диалоге: "Произошла ошибка:
'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)"

**Comment by sibskull** [comment]
Корни проблемы, похоже, такие же как https://github.com/bmakarenko/gost-crypto-gui/issues/1

**Comment by sibskull** [comment]
Причина в передаче неюникодной строки
https://github.com/bmakarenko/token-manager/blob/master/token-manager.py#L249
изменить на u'б/н' или вообще переходить на python3.
Там вылезет, правда, другая ошибка.

**Comment by bmakarenko** [comment]
Это да, маркер юникодовой строки надо было добавить, но эта строка вообще не должна выполняться если токенов или считывателей вообще нет.
Что выводит list_pcsc ?

**Comment by sibskull** [comment]
Токенов нет. Я пока без них решил проверить.

**Comment by bmakarenko** [comment]
Надо смотреть что выводит list_pcsc

**Comment by sibskull** [comment]
```
cas@cas cert2 $ list_pcsc
ACS ACR38U-CCID 00 00
cas@cas cert2 $ opensc-tool -l
# Detected readers (pcsc)
Nr.  Card  Features  Name
0    No              ACS ACR38U-CCID 00 00
```

**Comment by sibskull** [comment]
Это считыватель смарт-карт в клавиатуре.

**Comment by bmakarenko** [comment]
В таком случае, раз уж он определяется list_pcsc, маркер u должен починить эту проблему.

**Comment by sibskull** [comment]
Да, теперь исправлено.
