### ISSUE TITLE
'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by TurboBlaze** [bmakarenko/token-manager#6]
Здравствуйте.
Дистрибутив Porteus (на базе Slackware).
Установлен Token-manager 0.12-alt2.git1143028 и CryptoPro CSP 4

Список установленных пакетов:
```
consolehelper-0.3.2-alt1.x86_64.xzm
cprocsp-compat-debian_1.0.0-1_all.xzm
cprocsp-cpopenssl-64_4.0.0-4_amd64.xzm
cprocsp-cpopenssl-base_4.0.0-4_all.xzm
cprocsp-cpopenssl-devel_4.0.0-4_all.xzm
cprocsp-cpopenssl-gost-64_4.0.0-4_amd64.xzm
cprocsp-curl-64_4.0.0-4_amd64.xzm
cprocsp-drv-64-dummy_4.0.0-4_amd64.xzm
cprocsp-drv-devel_4.0.0-4_all.xzm
cprocsp-ipsec-devel_4.0.0-4_all.xzm
cprocsp-ipsec-esp-64-dummy_4.0.0-4_amd64.xzm
cprocsp-ipsec-genpsk-64_4.0.0-4_amd64.xzm
cprocsp-ipsec-ike-64_4.0.0-4_amd64.xzm
cprocsp-rdr-emv-64_4.0.0-4_amd64.xzm
cprocsp-rdr-esmart-64_4.0.0-4_amd64.xzm
cprocsp-rdr-gui-64_4.0.0-4_amd64.xzm
cprocsp-rdr-gui-gtk-64_4.0.0-4_amd64.xzm
cprocsp-rdr-inpaspot-64_4.0.0-4_amd64.xzm
cprocsp-rdr-mskey-64_4.0.0-4_amd64.xzm
cprocsp-rdr-novacard-64_4.0.0-4_amd64.xzm
cprocsp-rdr-pcsc-64_4.0.0-4_amd64.xzm
cprocsp-rdr-rutoken-64_4.0.0-4_amd64.xzm
cprocsp-rsa-64_4.0.0-4_amd64.xzm
cprocsp-stunnel-64_4.0.0-4_amd64.xzm
cprocsp-xer2print_4.0.0-4_all.xzm
ifd-rutokens_1.0.1_amd64.xzm
libpam0-1.3.0.0.17.7d0c-alt1.x86_64.xzm
libreoffice-5.3.1.2-x64-3.2-ru-1.xzm*
lsb-cprocsp-base_4.0.0-4_all.xzm
lsb-cprocsp-capilite-64_4.0.0-4_amd64.xzm
lsb-cprocsp-devel_4.0.0-4_all.xzm
lsb-cprocsp-kc1-64_4.0.0-4_amd64.xzm
lsb-cprocsp-kc2-64_4.0.0-4_amd64.xzm
lsb-cprocsp-pkcs11-64_4.0.0-4_amd64.xzm
lsb-cprocsp-rdr-64_4.0.0-4_amd64.xzm
lsb-cprocsp-rdr-accord-64_4.0.0-4_amd64.xzm
lsb-cprocsp-rdr-sobol-64_4.0.0-4_amd64.xzm
pam0-config-1.7.0-alt1.noarch.xzm
python-modules-2.7.11-alt4.x86_64.xzm
qt-4.8.7-x86_64-6.xzm
sip-4.19.2-x86_64-1.xzm
token-manager-0.12-alt2.git1143028.noarch.xzm
```

При запуске token-manager.py появляется окно с ошибкой 'NoneType' object has no attribute 'group' и такой вывод:
`root@porteus:~# python /usr/bin/token-manager.py

Qt: Session management error: None of the authentication protocols specified are supported
libpng warning: iCCP: known incorrect sRGB profile
An error occurred in running the program.
/dailybuildsbranches/CSP_4_0/CSPbuild/CSP/samples/support/cplevel.c:398:Cannot find default provider.

Error number 0x80090017 (2148073495).
Provider type not defined.
An error occurred in running the program.
/dailybuildsbranches/CSP_4_0/CSPbuild/CSP/samples/support/getcspparam.c:28:Can not get CSP param: AcquireContext failed.
Error number 0x80090017 (2148073495).
Provider type not defined.
An error occurred in running the program.
/dailybuildsbranches/CSP_4_0/CSPbuild/CSP/samples/csptest/ctkey.c:975:AcquireContext("null")
Error number 0x80090017 (2148073495).
Provider type not defined.
root@porteus:~#`

Тема на ALT Linux forum.altlinux.org/index.php?topic=39267.0

**Comment by bmakarenko** [comment]
token-manager не может выполнить эту команду и определить версию КриптоПро
/opt/cprocsp/bin/amd64/csptest -keyset -verifycontext
т.к. она завершается с ошибкой
У вас не выбран криптопровайдер по умолчанию. А судя по листингам на форуме, вы пытаетесь установить его от непривилегированного пользователя. 

Запустите от рута
/opt/cprocsp/sbin/amd64/cpconfig -defprov -setdef -provtype 75 -provname "Crypto-Pro GOST R 34.10-2001 KC1 CSP"
после чего проверьте команду выше.

**Comment by TurboBlaze** [comment]
Добрый вечер!
КриптоПро CSP-4.0.9914 установил заново в чистую систему.
От root такая же ошибка. Лог:
```
root@porteus:~# /opt/cprocsp/sbin/amd64/cpconfig -defprov -setdef -provtype 75 -provname "Crypto-Pro GOST R 34.10-2001 KC1 CSP"
root@porteus:~# ls /opt/cprocsp/bin/amd64/
certmgr*  cp-genpsk.sh*  cpverify*  cryptcp*  csptest*  csptestf*  curl*  der2xer*  genkpim*  genpsk*  inittst*  list_pcsc*  wipefile*
root@porteus:~# /opt/cprocsp/bin/amd64/csptest -keyset -verifycontext
An error occurred in running the program.
/dailybuildsbranches/CSP_4_0/CSPbuild/CSP/samples/support/cplevel.c:398:Cannot find default provider.

Error number 0x80090017 (2148073495).
Provider type not defined.
An error occurred in running the program.
/dailybuildsbranches/CSP_4_0/CSPbuild/CSP/samples/support/getcspparam.c:28:Can not get CSP param: AcquireContext failed.
Error number 0x80090017 (2148073495).
Provider type not defined.
An error occurred in running the program.
/dailybuildsbranches/CSP_4_0/CSPbuild/CSP/samples/csptest/ctkey.c:989:AcquireContext("null")
Error number 0x80090017 (2148073495).
Provider type not defined.
Total: SYS: 0.010 sec USR: 0.000 sec UTC: 0.000 sec
[ErrorCode: 0x80090017]
root@porteus:~# /opt/cprocsp/sbin/amd64/cpconfig -defprov -view -provtype 75
Listing Available Providers:
Provider type	Provider Name
_____________	_____________________________________

Provider types and provider names have been listed.
root@porteus:~# /opt/cprocsp/sbin/amd64/cpconfig -defprov -view_type
Listing Available Provider Types:
Provider type	Provider Type Name
_____________	_____________________________________
root@porteus:~# cp /etc/opt/cprocsp/config64.ini{,.bak}
```

Здесь я заменил содержимое /etc/opt/cprocsp/config64.ini на https://pastebin.com/B3r2QCFW
После чего криптопровайдер Crypto-Pro GOST R 34.10-2001 KC1 CSP появился в списке, если проверить командой /opt/cprocsp/sbin/amd64/cpconfig -defprov -view -provtype 75
Лог, увы не скопироал.

```
root@porteus:~# ls /etc/opt/cprocsp/
config64.ini  config64.ini.bak  release  stunnel.conf*
root@porteus:~# python /usr/bin/token-manager.py
Qt: Session management error: Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed
libpng warning: iCCP: known incorrect sRGB profile
An error occurred in running the program.
/dailybuildsbranches/CSP_4_0/CSPbuild/CSP/samples/support/cplevel.c:398:Cannot find default provider.

Error number 0x80090017 (2148073495).
Provider type not defined.
An error occurred in running the program.
/dailybuildsbranches/CSP_4_0/CSPbuild/CSP/samples/support/getcspparam.c:28:Can not get CSP param: AcquireContext failed.
Error number 0x80090017 (2148073495).
Provider type not defined.
An error occurred in running the program.
/dailybuildsbranches/CSP_4_0/CSPbuild/CSP/samples/csptest/ctkey.c:989:AcquireContext("null")
Error number 0x80090017 (2148073495).
Provider type not defined.
root@porteus:~#
```

Скриншот http://s5.uploads.ru/X9UoS.png

**Ссылка с готовой сборкой Porteus (включает КриптоПро CSP-4.0.9914 и token-manager)** - http://www.mediafire.com/file/a6c3vac7c3yk7e0/Porteus-CINNAMON-v3.2.2-ru-CSP-x86_64.iso
Для авторизации под root в терминале необходимо набрать **su** и пароль **toor**
Для удобства, чтобы неустанавливать, можно протестировать данный iso-образ в виртуальной машине, например в VirtualBox.
Инструкция как установить Porteus http://forum.porteus.org/viewtopic.php?f=54&t=208

**Comment by TurboBlaze** [comment]
Спасибо разобрался, это баг КриптоПро - для Porteus неправильно генерируется /etc/opt/cprocsp/config64.ini
В итоге все завелось http://se.uploads.ru/doeHF.png
