### ISSUE TITLE
Ошибка в Операции > Ввод лицензии КриптоПро CSP и в Операции > Просмотр лицензии КриптоПро CSP

### ISSUE THREAD

**Issue by TurboBlaze** [bmakarenko/token-manager#8]
Если зайти в Операции > Ввод лицензии КриптоПро CSP и в Операции > Просмотр лицензии КриптоПро CSP, то в терминале такая ошибка:

```
Traceback (most recent call last):
  File "/usr/bin/token-manager.py", line 885, in enter_license
    l = set_license(cpro_license)
  File "/usr/bin/token-manager.py", line 326, in set_license
    stdout=subprocess.PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] Нет такого файла или каталога
Invalid license serial number.
 
Error code:2
```

Если ввести лицензию штатными средствами КриптоПро и зайти в данные вкладки повторно, то такой ошибки нет.

**Comment by bmakarenko** [comment]
Дело в том, что для установки лицензии КриптоПро требуются права root. В Гослинукс при установке пакета создается симлинк /usr/bin/cpconfig-amd64 указывающий на consolehelper, который позволяет вызвать графическое диалоговое окно с полем ввода пароля root.
Если вы используете token-manager в АльтЛинукс - обратитесь к мейнтейнеру пакета Андрею Черепанову.
